# (default.conf) Nginx configuration file - Proxy reverso para o serviço de backend (email-worker)
# O proxy reverso é configurado para encaminhar as requisições recebidas na porta 80 para o serviço de backend (email-worker) na porta 8080. Normalmente, o serviço de backend é onde a aplicação de envio de e-mails está rodando, e o Nginx atua como um intermediário para gerenciar as requisições e melhorar a performance e segurança.
# Em geral um proxy reverso é usado para:
# - Balanceamento de carga: Distribuir as requisições entre múltiplas instâncias do serviço de backend para melhorar a performance e disponibilidade.
# - Segurança: O proxy reverso pode atuar como uma camada de segurança, filtrando requisições maliciosas antes que elas alcancem o serviço de backend.
server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    location /api {
        proxy_pass http://app:8080/; # Encaminha as requisições para o serviço de backend (email-worker)
        proxy_http_version 1.1;
    }
}